default: &default
  adapter: 'postgresql'
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 70 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWD'] %>
  port: <%= ENV['DB_PORT'].presence || 5432 %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  url:

development:
  <<: *default
  database: turbopay_dev

test:
  <<: *default
  database: turbopay_test

staging:
  timeout: 5000
  <<: *default

production:
  timeout: 5000
  database: <%= ENV['DB_NAME'] %>
  <<: *default
